### ISSUE TITLE
Regional forme type mismatch

### ISSUE THREAD

**Issue by bobpaw** [jpgualdarrama/PokeFarmQoL#31]
Presumably this also applies to any Pokémon eggs which have forms of a different type, Sandshrew and Darmanitan being obvious examples. As shown in image 2, it does not affect Pokémon -- only eggs.
![image](https://user-images.githubusercontent.com/27317753/84608000-f0a56800-ae75-11ea-9cba-7a8b44cef77c.png)
![image](https://user-images.githubusercontent.com/27317753/84608080-585bb300-ae76-11ea-9633-5a59a30775cb.png)

**Comment by jpgualdarrama** [comment]
Thanks for documenting this, this is something I've known about but haven't written down. This is due to 2 reasons:
1) The information presented in the HTML for the egg is pretty limited; it consists of the species' name (no form information) and the image of the egg
2) The data structure used originally by Bento to get the type information about each pokemon and egg relies on the Pokedex page. One of the quirks of the Pokedex page is that it only stores the type(s) of the _last viewed form_ of a pokemon. So, in the case of Vulpix, if the last form of Vulpix that you viewed was the Alolan form and that is what was stored by the script, all Vulpix eggs will be highlighted as being Ice type.

That is not to say that it is not fixable, just wanted to provide some background on the issue.

**Comment by bobpaw** [comment]
I have compiled a list of all Pokemon with regional formes at (this gist)[https://gist.github.com/bobpaw/c1d5f047268af7ecc954106bb8b76f28]. Meowth is on there twice because it has both a Galarian and Alolan forme.

**Comment by bobpaw** [comment]
[This other gist](https://gist.github.com/bobpaw/48ba18af4894ca4c0846030990ddcfae) has an example oneliner using Pokefarm's ajax function to get the dex data for a single Pokemon. While it presents a possible route to fixing the issue, it would make gathering the dex info for pokemon incredibly longer. Because we have a list of regional formes, it's most likely easier to just manually add exceptions.

**Comment by jpgualdarrama** [comment]
Thanks for providing the gists. The approach I've taken up to now when it comes to building up lists of pokemon or data about pokemon (e.g., number of evolutions remaining,) is to find away to build the list programmatically. Now that the script has a feature to load every pokemon's dex page from the QoL Hub, I see an opportunity to generate the list of mons with regional forms from the dex pages. So what I'm thinking is, I'll put the list you collected into the code, and I'll also add code to the "Update Pokedex" button to generate the list dynamically.

Really the main reason I want to be able to build up the list in the code is so that no one has to go back and update things manually when new pokemon (official or exclusive variants) get added.

**Comment by jpgualdarrama** [comment]
Because the shelter page's HTML doesn't provide any information on eggs besides the egg's name and the URL to the png file, I think the most foolproof way to sort this out that won't require any manual updating of lists is to store a map of each egg's png to its types. Like I was saying above, the code behind the "Update Pokedex" button already loads data from pokefarm.com/dex/* so this will just require more that data to be processed and stored.

**Comment by jpgualdarrama** [comment]
Promoted a fix to fully differentiate between eggs with the same name and different types based on the URL to the png file.
![image](https://user-images.githubusercontent.com/7121719/91381265-fb289a00-e7f4-11ea-93bc-30c3ef919d50.png)
![image](https://user-images.githubusercontent.com/7121719/91381284-0aa7e300-e7f5-11ea-9723-1aa54dd70440.png)

**Comment by jpgualdarrama** [comment]
No issues reported; closing
